# COLDIRON OS — driver blacklist
#
# Makes networking and peripheral exfiltration channels extremely difficult
# to enable accidentally. NOTE: this is NOT the same as a kernel compiled
# without networking — that is the v0.2 milestone (custom kernel).

# ---- wired NICs ----
blacklist e1000
blacklist e1000e
blacklist e100
blacklist r8169
blacklist r8152
blacklist igb
blacklist igc
blacklist i40e
blacklist ixgbe
blacklist bnx2
blacklist bnx2x
blacklist tg3
blacklist forcedeth
blacklist sky2
blacklist rtl8139
blacklist via-rhine
blacklist virtio_net
blacklist vmxnet3
blacklist veth

# ---- wireless ----
blacklist cfg80211
blacklist mac80211
blacklist ath9k
blacklist ath10k_pci
blacklist ath11k_pci
blacklist iwlwifi
blacklist iwlmvm
blacklist iwl3945
blacklist iwl4965
blacklist rtlwifi
blacklist rtl8xxxu
blacklist rtl8192cu
blacklist mt76
blacklist mt76x2u
blacklist mwifiex_pcie
blacklist libertas

# ---- USB / WWAN networking ----
blacklist usbnet
blacklist cdc_ether
blacklist cdc_ncm
blacklist cdc_mbim
blacklist rndis_host
blacklist ax88179_178a
blacklist hso
blacklist qmi_wwan
blacklist wwan

# ---- Bluetooth / FireWire / Thunderbolt (exfiltration channels) ----
blacklist bluetooth
blacklist btusb
blacklist btbcm
blacklist btintel
blacklist btrtl
blacklist firewire_ohci
blacklist firewire_core
blacklist thunderbolt
blacklist thunderbolt_net
