#!/usr/bin/env bash
#
# build.sh — COLDIRON OS one-command ISO builder.
#
# Builds the hardened offline cold-storage live ISO with live-build.
#
# Usage:
#   sudo ./build.sh          # full build (fetch + config + build)
#   sudo ./build.sh clean    # clean previous build artifacts (config kept)
#
# Requirements:
#   - Debian/Ubuntu host (tested on Debian 12+)
#   - root privileges (live-build/debootstrap requirement)
#   - ~10 GB free disk, 4 GB+ RAM
#   - Internet access on the BUILD machine only (the target ISO has none)
#
set -euo pipefail

cd "$(dirname "$0")"

VERSION="0.1.0"
DISTRIBUTION="trixie"
ARCH="amd64"
OUT="dist/coldiron-os-${VERSION}-${ARCH}.iso"

# ---------------------------------------------------------------- helpers
say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then
      exec sudo "$0" "$@"
    fi
    echo "ERROR: the build must run as root (live-build requires it)." >&2
    echo "       Re-run with: sudo ./build.sh" >&2
    exit 1
  fi
}

# ---------------------------------------------------------------- prereqs
need_root "$@"

if ! command -v lb >/dev/null 2>&1 || ! command -v debootstrap >/dev/null 2>&1; then
  say "Installing live-build and debootstrap..."
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq live-build debootstrap curl
fi
# debootstrap needs a FRESH Debian archive keyring: the one bundled with
# Ubuntu hosts is too old to verify ${DISTRIBUTION}'s signing keys, so
# refresh it from Debian's own pool (checking for trixie's EDDSA key).
if ! gpg --no-default-keyring --keyring /usr/share/keyrings/debian-archive-keyring.gpg \
     --list-keys 41587F7DB8C774BCCF131416762F67A0B2C39DE4 >/dev/null 2>&1; then
  say "Refreshing debian-archive-keyring from the Debian pool (Ubuntu's is too old for ${DISTRIBUTION})..."
  DAK_DEB="$(curl -fsSL https://ftp.debian.org/debian/pool/main/d/debian-archive-keyring/ \
             | grep -oE 'debian-archive-keyring_[0-9.]+_all\.deb' | sort -V | tail -n 1)"
  curl -fsSL "https://ftp.debian.org/debian/pool/main/d/debian-archive-keyring/${DAK_DEB}" -o /tmp/dak.deb
  dpkg -i /tmp/dak.deb
  rm -f /tmp/dak.deb
fi

# ---------------------------------------------------------------- fetch + verify third-party binaries
say "Fetching and verifying third-party binaries (Sparrow Wallet)..."
./scripts/fetch-binaries.sh

# ---------------------------------------------------------------- clean (optional)
if [ "${1:-}" = "clean" ]; then
  say "Cleaning previous build (config kept)..."
  lb clean 2>/dev/null || true
fi

# ---------------------------------------------------------------- configure
say "Configuring live-build (${DISTRIBUTION}/${ARCH})..."
lb config \
  --mode debian \
  --distribution "${DISTRIBUTION}" \
  --archive-areas "main contrib non-free-firmware" \
  --linux-flavours "${ARCH}" \
  --binary-image iso-hybrid \
  --debian-installer false \
  --iso-application "COLDIRON OS" \
  --iso-volume "COLDIRON OS" \
  --iso-preparer "COLDIRON Project" \
  --iso-publisher "COLDIRON Project" \
  --memtest none \
  --firmware-binary false \
  --firmware-chroot false \
  --bootappend-live "boot=live config toram noswap noresume quiet loglevel=3 ipv6.disable=1" \
  --apt-indices false \
  --apt-options "-y --option Acquire::Retries=3" \
  --cache true

# lb config is idempotent: it PRESERVES values already in config/chroot.
# A stale run left LB_UNION_FILESYSTEM="aufs" (no aufs module in Debian
# kernels — boot would fail), while this live-build defaults to overlay.
# Force overlay here so the binary stage renders union=overlay.
sed -i 's/^LB_UNION_FILESYSTEM=.*/LB_UNION_FILESYSTEM="overlay"/' config/chroot
grep -q '^LB_UNION_FILESYSTEM="overlay"' config/chroot \
  || echo 'LB_UNION_FILESYSTEM="overlay"' >> config/chroot

# live.list.chroot is generated by lb config with a sysvinit default
# (live-config-sysvinit + sysvinit-core) that CONFLICTS with trixie's
# systemd base: live-config pulls the systemd backend, sysvinit-core
# Conflicts systemd-sysv, and the whole resolution aborts. Override it
# with the systemd variant (lb config only creates the file if missing,
# so this stays in effect for subsequent runs).
cat > config/package-lists/live.list.chroot <<'EOF'
live-boot
live-config
live-config-systemd
EOF

# ---------------------------------------------------------------- build
# lb build does NOT detect config changes: if a previous build left the
# binary stage stamped "done", a new bootappend/template change would be
# silently ignored and the ISO would be stale. Force a binary-stage redo
# every time (the chroot stage stays cached). Cost: ~5-10 min.
say "Cleaning binary stage (config may have changed)..."
lb clean --binary 2>/dev/null || true

say "Building ISO (15-60 minutes, depending on the machine)..."
lb build

mkdir -p dist
mv -f "live-image-${ARCH}.hybrid.iso" "${OUT}"

say "Build complete."
echo "  ISO:       ${OUT}"
echo "  Size:      $(du -h "${OUT}" | cut -f1)"
echo "  SHA256:    $(sha256sum "${OUT}" | cut -d' ' -f1)"
echo
echo "Next steps:"
echo "  ./scripts/qemu-test.sh ${OUT}     # headless smoke test"
echo "  dd if=${OUT} of=/dev/sdX bs=4M status=progress   # write to USB"
